### ISSUE TITLE
Please support helper template switches

### ISSUE THREAD

**Issue by DavidSpivey** [Luligu/matterbridge-hass#51]
I understand that this plugin supports switches that are boolean. But in order to make such a switch do something interesting, it requires an automation (afaik). In HA I can create a switch from helpers and immediately start telling the switch what I want it to do (program-in-place).

I currently use template switches to convert 433mhz signals to a switch. I have many of these template switches and would prefer not to create a new automation and boolean switch just to expose them via matter.

**Comment by Luligu** [comment]
Hi,
Make me please a copy / screenshot of this entity please so I understand what you need...

**Comment by Luligu** [comment]
Hi,
I'm finally working on the plugin.

I will do all in the list and keep you updated in Discord if you join.

I will start with this:
```
switch:
  - name: "My Template Switch"
    unique_id: my_template_switch
    icon: mdi:power-plug 
    state: "{{ 'on' if is_state('switch.shelly_1pm_gen4','on') else 'off' }}"
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.shelly_1pm_gen4
    turn_off:
      service: switch.turn_off
      target:
        entity_id: switch.shelly_1pm_gen4
```
